### ISSUE TITLE
Icons (Emojis, HTML, etc.) Drift From Location When Map Scale Changes

### ISSUE THREAD

**Issue by reggie3** [reggie3/react-native-webview-leaflet#8]
When the map is zoomed, markers drift from their original location.

**Comment by reggie3** [comment]
Fixed in version 2.

**Comment by Jheruz** [comment]
Hello! The problem still persist even in version 5.0.2
the ownPositionMarker and mapMarkers still drift in map when zoom too far
